### PR TITLE
update chat room to be general.

### PR DESCRIPTION
**Pull request by nelsonic**
instead of having multiple chat rooms we have one.

### CODE REVIEW

**Comment by nelsonic** [comment]
@iteles any comments...?

**Comment by iteles** [comment]
@nelsonic One js best practices room seems sensible.
Are you suggesting this replaces all possible docdis chat rooms?

**Comment by nelsonic** [comment]
Would a docdis/chat repo be better?

(only just saw you had commented now...)

**Comment by iteles** [comment]
Well, `/chat` would be more intuitive, but less prescriptive ("let's just chat about JS"). It depends which one you want to be.

**Comment by nelsonic** [comment]
Which is more Shoshin...?

**Comment by iteles** [comment]
`/chat` shows more openness.

**Comment by nelsonic** [comment]
agree. please create the repo and make it public/open. thanks.

**Comment by iteles** [comment]
I went with creating a public channel in gitter, I don't think we need a _repo_ for chat, just the channel.
Let me know if you want me to do this a different way. 
Updated readme with new link :+1:

**Comment by nelsonic** [comment]
If that works, go for it! :-)

**Comment by iteles** [comment]
@nelsonic Should we be adding this badge and specific channel to every docdis readme?

**Pull request merged**
